repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python -m mypy custom_components/tplink_deco
        language: system
        types: [python]
        pass_filenames: false
